steps:

# Access the id_github file from Secret Manager, and setup SSH
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --recurse-submodules
  - git@github.com:asilas-soap/lerna-started-example
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - checkout
  - main
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - log
  volumes:
  - name: 'ssh'
    path: /root/.ssh

availableSecrets:
  secretManager:
  - versionName: projects/soaphealth-development/secrets/SSH_KEY/versions/latest
    env: 'SSH_KEY'

# # Access the id_github file from Secret Manager
# - name: "gcr.io/cloud-builders/gcloud"
#   args: [
#     "secrets",
#     "versions",
#     "access",
#     "latest",
#     "--secret",
#     "SSH_KEY",
#     "--out-file=/root/.ssh/id_github"
#   ]
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh

# # Set up git with key and domain
# - name: node
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     chmod 600 /root/.ssh/id_github
#     cat <<EOF >/root/.ssh/config
#     HostName github.com
#     User asilas@soap.health
#     IdentityFile /root/.ssh/id_github
#     EOF
    
#     echo "cat /root/.ssh/config----------------------"
#     cat /root/.ssh/config
#     ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh

# - name: node
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |

#     echo "config user-------------------------------------------------------------------"
#     git config --global user.name Alberto Silas
#     git config --global user.email asilas@soap.health

#     echo "Cloning repo ..."
#     git clone --depth 1 git@github.com:asilas-soap/lerna-started-example.git
    
#     echo "git checkout main"
#     git checkout main

#     echo "Updating image tag version ..."
#     cd lerna-started-example
#     ls
#     yarn install

#     echo "node command"
#     node ./deployment-pipeline/index.js

#     echo "Pushing changes to git config repo ..."

#     echo "git add -A  ----------------------------------------------------------------------------"
#     git add -A

#     echo "git status ----------------------------------------------------------------------------"
#     git status

#     echo "git commit ----------------------------------------------------------------------------"
#     git commit -m "commit from a"

#     echo "git push ----------------------------------------------------------------------------"
#     git push origin master
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh
# - name: node
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     git config --global init.defaultBranch main

#     echo "git config-------------"
#     git config --global advice.detachedHead false
#     git config --global user.email "asilas@soap.health"
#     git config --global user.name "Alberto Silas"
    
#     echo "git remote remove origin"
#     git remote remove origin

#     echo "git remote add"
#     git remote add origin git@github.com:asilas-soap/lerna-started-example.git

#     echo "git pull --ff-only"
#     git pull --ff-only

#     echo "git branch --set-upstream-to=origin/main"
#     git branch --set-upstream-to=origin/main

#     echo "git status"
#     git status

#     # git config --global url."https://github.com/".insteadOf "git://github.com/"
    
#     # echo "git pull origin main--------------"
#     # git pull origin main

#     echo "git checkout main--------------"
#     git checkout main

#     echo "git remote -v"
#     git remote -v
    
#     ls /root/.ssh
#     echo "git status----------"
#     git status
#     echo "install------------------"
#     yarn install
#     ls
#     node ./deployment-pipeline/index.js
#     echo "git add ."
#     git add .
#     echo "git status"
#     git status
#     "git commit"
#     git commit -m "commit from cb"
#     echo "git push origin main"
#     git push origin main
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh


# - name: node
#   entrypoint: yarn
#   args: ['install']

# - name: node
#   args: ['index.js']
#   dir: "deployment-pipeline"
# # - name: "gcr.io/cloud-builders/git"
# #   args: ["remote", "set-url", "origin", "https://asilas-soap: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@github.com/$REPO_FULL_NAME.git"]
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
#   entrypoint: 'git'
#   args: ['clone', 'https://asilas-soap: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@github.com/$REPO_FULL_NAME.git']

# # - name: "gcr.io/cloud-builders/git"
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
#   entrypoint: 'git'
#   args: ["checkout", "$BRANCH_NAME"]
  
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
#   entrypoint: 'git'
#   args: ["pull", "--unshallow", "--tags", "--ff-only"]

# - name: node
#   entrypoint: yarn
#   args: ['install']

# # - name: "gcr.io/cloud-builders/git"
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
#   entrypoint: 'git'
#   args: ["config", "--global", "user.email", "asilas@soap.health"]

# # - name: "gcr.io/cloud-builders/git"
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
#   entrypoint: 'git'
#   args: ["config", "--global", "user.name", "Alberto Silas"] 

# - name: node
#   args: ['index.js']
#   dir: "deployment-pipeline"

# # - name: "gcr.io/cloud-builders/git"
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
#   entrypoint: 'git'
#   args: ["add", "."]


timeout: "5000s"
options:
  logging: CLOUD_LOGGING_ONLY