steps:

# Access the id_github file from Secret Manager, and setup SSH
steps:

# Access the id_github file from Secret Manager
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'gcloud secrets versions access latest --secret=SSH_KEY > /root/.ssh/id_github' ]
  volumes:
  - name: 'ssh'
    path: /root/.ssh
    
# Set up git with key and domain
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_github
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_github
    EOF
    ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/bash
  args: 
  - -c
  - |
    git clone git@github.com:asilas-soap/lerna-started-example.git --depth 1
    ls
    cd lerna-started-example
    git config --global user.email "asilas@soap.health"
    git config --global user.name "Alberto Silas"
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: "node:20.10.0"
  id: "install"
  entrypoint: "yarn"
  args: ["install"]
  dir: "lerna-started-example"

- name: "node:20.10.0"
  id: "build"
  entrypoint: "yarn"
  args: ["lerna", "run", "build"]
  dir: "lerna-started-example"

- name: "node:20.10.0"
  id: "version"
  entrypoint: "yarn"
  args: ["lerna", "version", "--yes", "--conventional-commits"]
  dir: "lerna-started-example"
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: "node:20.10.0"
  id: "release"
  entrypoint: "yarn"
  args: ["run", "conventional-github-releaser", "-p", "angular"]
  env:
  - 'CONVENTIONAL_GITHUB_RELEASER_TOKEN=${_GH_TOKEN}'
  dir: "lerna-started-example"
  volumes:
  - name: 'ssh'
    path: /root/.ssh

timeout: "5000s"
options:
  logging: CLOUD_LOGGING_ONLY