steps:

# Edit Kustomize layer in config repo and push changes
# - name: gcr.io/cloud-builders/git
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     echo "Cloning repo ..."
#     git checkout main
#     git status
#     ls
#     node /deployment-pipeline/index.js
#     git status

# - name: node
#   entrypoint: yarn
#   args: ['install']

# - name: node
#   args: ['index.js']
#   dir: "deployment-pipeline"


# Access the id_github file from Secret Manager
- name: "gcr.io/cloud-builders/gcloud"
  args: [
    "secrets",
    "versions",
    "access",
    "latest",
    "--secret",
    "SSH_KEY",
    "--out-file=/root/.ssh/id_github"
  ]
  dir: "packages/libs/database/prisma"
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Set up git with key and domain
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_github
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_github
    EOF
    ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: node
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git clone --depth 1 git@github.com:asilas-soap/lerna-started-example.git .
    git checkout main
    ls
    git status
    echo "install"
    yarn install
    ls
    git status
    node ./deployment-pipeline/index.js
  volumes:
  - name: 'ssh'
    path: /root/.ssh


availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/SSH_KEY/versions/latest   
    env: 'SSH_KEY'

# # - name: "gcr.io/cloud-builders/git"
# #   args: ["remote", "set-url", "origin", "https://asilas-soap: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@github.com/$REPO_FULL_NAME.git"]
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
#   entrypoint: 'git'
#   args: ['clone', 'https://asilas-soap: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@github.com/$REPO_FULL_NAME.git']

# # - name: "gcr.io/cloud-builders/git"
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
#   entrypoint: 'git'
#   args: ["checkout", "$BRANCH_NAME"]
  
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
#   entrypoint: 'git'
#   args: ["pull", "--unshallow", "--tags", "--ff-only"]

# - name: node
#   entrypoint: yarn
#   args: ['install']

# # - name: "gcr.io/cloud-builders/git"
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
#   entrypoint: 'git'
#   args: ["config", "--global", "user.email", "asilas@soap.health"]

# # - name: "gcr.io/cloud-builders/git"
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
#   entrypoint: 'git'
#   args: ["config", "--global", "user.name", "Alberto Silas"] 

# - name: node
#   args: ['index.js']
#   dir: "deployment-pipeline"

# # - name: "gcr.io/cloud-builders/git"
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
#   entrypoint: 'git'
#   args: ["add", "."]

# # - name: "gcr.io/cloud-builders/git"
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
#   entrypoint: 'git'
#   args: ["commit", "-m", "message c"]

# # - name: "gcr.io/cloud-builders/git"
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
#   entrypoint: 'git'
#   args: ["tag", "-a", "v0.51.0", "-m", "v0.51.0"]

# # - name: "gcr.io/cloud-builders/git"
# #   args: ["push", "origin", "main", "--follow-tags"]
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
#   entrypoint: 'git'
#   args: ["push", "origin", "main", "--follow-tags"]

timeout: "5000s"
options:
  logging: CLOUD_LOGGING_ONLY