steps:

# Access the id_github file from Secret Manager, and setup SSH
steps:

- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/bash
  args: 
  - -c
  - |
    git clone git@github.com:asilas-soap/lerna-started-example.git --depth 1
    ls
    cd lerna-started-example
    git config --global user.email "asilas@soap.health"
    git config --global user.name "Alberto Silas"
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: "node:20.10.0"
  id: "install"
  entrypoint: "yarn"
  args: ["install"]
  dir: "lerna-started-example"

- name: "node:20.10.0"
  id: "build"
  entrypoint: "yarn"
  args: ["lerna", "run", "build"]
  dir: "lerna-started-example"

- name: "node:20.10.0"
  id: "version"
  entrypoint: "yarn"
  args: ["lerna", "version", "--yes", "--conventional-commits"]
  dir: "lerna-started-example"
  volumes:
  - name: 'ssh'
    path: /root/.ssh

availableSecrets:
  secretManager:
  - versionName: projects/soaphealth-development/secrets/SSH_KEY/versions/latest
    env: 'SSH_KEY'

timeout: "5000s"
options:
  logging: CLOUD_LOGGING_ONLY